### ISSUE TITLE
Error launching the app

### ISSUE THREAD

**Issue by nkov** [bkanber/Slackadaisical#1]
When running `$ npm run start` or when the package is installed globally, I get an error:

```bash
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Request._callback (.../Slackadaisical/dist/SlackAPI.js:197:55)
    at Request.self.callback (.../Slackadaisical/node_modules/request/request.js:186:22)
    ...
```

I tried rebuilding the `dist/` directory with the same error.

Using node 7.6.0 on OSX 10.12.

**Comment by bkanber** [comment]
I believe this is an issue with your Slack API token, it is unable to fetch your channels from the API. 

Can you please try this API request from the browser or curl or postman and let me know if/what error you get? 
```
https://slack.com/api/conversations.list?token={YOUR_TOKEN_HERE}&exclude_archived=true&limit=500&types=public_channel%2Cprivate_channel%2Cmpim%2Cim&pretty=1
```

**Comment by ranmeirman** [comment]
Getting the same error. I tried the request on postman and got:
```
{
    "ok": false,
    "error": "internal_error"
}
```
I tried re-issuing the token several times and always failed.

**Comment by nkov** [comment]
@bkanber I tried that and getting the same error as posted by @ranmeirman

**Comment by tom-i** [comment]
Looks that this error still hasn't been fixed yet :-/
